"""Emit a Docker Compose fragment for a credproxy proxy sidecar.

The one deliberately Compose-aware corner of credproxy: everything else is
parent-agnostic (a proxy is just a container speaking the admin/bootstrap HTTP
contract), but a health-gated Compose sidecar is common enough to scaffold.

Every port and mount-target path comes from the proxy image's ENV contract
(`ImageEnv`, read via `docker inspect`) -- the same single source of truth the
managed lifecycle uses -- so a bumped image can't leave a stale literal here. The
service mirrors what `lifecycle.create_proxy` passes: NET_ADMIN, a mode-1777
tmpfs for the pushed config, the read-only token bind, and an ephemeral loopback
admin port. The healthcheck probes `/ready` (creds-ready), NOT `/health`
(capture-ready), so a Compose `service_healthy` gate opens only once credentials
have been pushed -- the whole point of the two-signal split (#41).

The probe is a `python -c` urllib one-liner: the proxy image ships python but no
curl/wget, and `urlopen` raises (nonzero exit) on any non-200, which is exactly
the readiness semantic.
"""
from __future__ import annotations

from .imageenv import ImageEnv


def emit_compose(meta: ImageEnv, image_tag: str, token_source: str,
                 token_note: str | None = None) -> str:
    """Return the Compose fragment as a formatted YAML string (no YAML library --
    it is a fixed template with a handful of substitutions).

    - `meta`      the proxy image's ENV contract (ports + mount targets).
    - `image_tag` the tag baked into the emitted `image:` line.
    - `token_source` the host path bind-mounted at the token target -- a real
      `<state>/auth.token` (NAME given) or a `${CREDPROXY_STATE:?...}` reference
      (no NAME) for a Compose `.env` to interpolate.
    - `token_note` an extra comment line above the token bind (used by the
      no-NAME form to say where `CREDPROXY_STATE` points)."""
    port = meta.http_port
    # The /ready urllib probe. urlopen raises HTTPError on the 503 that /ready
    # returns until a config is pushed -> nonzero exit -> unhealthy, so no
    # try/except is needed; a 200 hits sys.exit(0).
    probe = (
        f"import urllib.request,sys; "
        f"sys.exit(0 if urllib.request.urlopen("
        f"'http://127.0.0.1:{port}/ready', timeout=3).status == 200 else 1)"
    )
    note = f"      {token_note}\n" if token_note else ""
    # The service-level `tmpfs` short form maps `path:options` straight to moby's
    # HostConfig.Tmpfs, parsed identically to `docker run --tmpfs` -- so this is
    # byte-for-byte the option string the managed path passes (lifecycle), which
    # sidesteps the long-form `tmpfs.mode` octal-vs-decimal ambiguity.
    tmpfs_opt = f"{meta.tmpfs}:size=64k,mode=1777"
    return f"""\
# Docker Compose fragment: a credproxy proxy sidecar + your workspace service.
# Generated by `credproxy emit-compose`. Ports and paths come from the proxy
# image's ENV contract (docker inspect) -- regenerate after `credproxy dev build`
# if you bump them. This is pure convenience; the YAML is yours to edit.
#
# The proxy owns the shared network namespace and holds NET_ADMIN; the workspace
# service joins it with `network_mode: "service:proxy"` and waits on a
# `service_healthy` gate that opens only once you have pushed credentials:
#     docker compose up -d proxy
#     credproxy workspace NAME push        # or: credproxy push --admin ... --config ... --token ...
#     docker compose up -d workspace
services:
  proxy:
    image: {image_tag}
    cap_add:
      - NET_ADMIN                 # install iptables in the shared netns
    tmpfs:
      # Pushed config lives here; mode 1777 so the proxy's unprivileged uid can
      # write config.json (byte-for-byte credproxy's managed --tmpfs string).
      - {tmpfs_opt}
    volumes:
      # Host-owned bearer token, bind-mounted read-only; the proxy reads it fresh
      # on every admin request and `credproxy push` authenticates with it.
{note}      - {token_source}:{meta.token}:ro   # on an enforcing-SELinux host append ,Z
    ports:
      # Admin API on an EPHEMERAL loopback host port (like credproxy's managed
      # -p 127.0.0.1:0:...); `credproxy push` resolves the live port via docker.
      - "127.0.0.1::{port}"
    healthcheck:
      # Gate on /ready (creds-ready), NOT /health (capture-ready): the workspace
      # starts only after a config has been pushed. The image has python, no curl.
      test:
        - CMD
        - python
        - -c
        - "{probe}"
      interval: 2s
      timeout: 5s
      retries: 60
      start_period: 5s

  # Your workspace service -- your own image, unmodified. The two credproxy lines
  # are network_mode + the health-gated depends_on:
  workspace:
    image: your-workspace-image      # <-- replace with your image
    network_mode: "service:proxy"    # share the proxy's network namespace
    depends_on:
      proxy:
        condition: service_healthy   # wait until credentials are pushed (/ready)
"""
