"""HTTP API: admin endpoints + shared AppState + middleware.

Single aiohttp listener on 0.0.0.0:CREDPROXY_HTTP_PORT serves both this
module's admin routes and bootstrap.py's workspace-facing routes.
Workspace reaches it via the iptables sentinel:80 -> port redirect;
host reaches it via docker -p 127.0.0.1:port.

Trust model:
- /admin/config requires `Authorization: Bearer <token>` matching the
  host-side .run/auth.token, bind-mounted read-only into the proxy at
  $CREDPROXY_TOKEN_PATH. The file is read fresh on every request, so
  rotating the host file takes effect without a proxy restart.
- fetch_metadata_guard rejects cross-origin browser requests; together
  with Chrome's Private Network Access default-deny (we never set
  Access-Control-Allow-Private-Network), this covers the browser
  threat without a shared secret.

Lifecycle: the token is owned by the host (.run/auth.token, mode 0644,
generated by `credproxy start` if absent) and bind-mounted read-only
into the proxy. Config lives on tmpfs at $CREDPROXY_TMPFS/config.json
-- survives SIGHUP-triggered python re-exec (`credproxy reload`);
re-pushed by `credproxy config` after a full container restart.
"""
import hmac
import json
import os
from dataclasses import dataclass, field
from pathlib import Path

from aiohttp import web

import config
import log
import pg
from config import BindingCredentials, Credentials
from pg import PgCredentials

TOKEN_PATH = Path(os.environ["CREDPROXY_TOKEN_PATH"])
CONFIG_PATH = Path(os.environ["CREDPROXY_TMPFS"]) / "config.json"


@dataclass
class AppState:
    creds: Credentials = field(default_factory=lambda: BindingCredentials({}))
    # The PostgreSQL broker's bindings (the `pg_bindings` wire section). Loaded
    # and swapped alongside `creds` on each accepted push, under the SAME
    # generation counter; the broker live-reads this per connection.
    pg_creds: PgCredentials = field(default_factory=lambda: pg.EMPTY)
    # Monotonic count of accepted (validated) config pushes. 0 == no config ever
    # accepted; >= 1 == creds-ready (what `/ready` gates on). Persisted inside the
    # tmpfs config envelope so it survives a SIGHUP re-exec (the tmpfs lives on);
    # a docker stop/start clears the tmpfs and correctly resets it to 0.
    generation: int = 0


STATE_KEY: web.AppKey[AppState] = web.AppKey("state", AppState)


def load_initial_state() -> AppState:
    """Boot-time sanity check + optional config load.

    The token is re-read per request, not stored; this just fails fast
    if the bind mount is missing or empty.
    """
    if not TOKEN_PATH.exists():
        raise SystemExit(
            f"[admin] {TOKEN_PATH} missing -- expected the host token to "
            f"be bind-mounted at this path"
        )
    if not TOKEN_PATH.read_text().strip():
        raise SystemExit(f"[admin] {TOKEN_PATH} is empty")

    if not CONFIG_PATH.exists():
        return AppState()
    try:
        raw = json.loads(CONFIG_PATH.read_text())
        creds = config.load_resolved(raw, source=str(CONFIG_PATH))
        pg_creds = pg.load_pg(raw, source=str(CONFIG_PATH),
                              reserved=pg.reserved_names(creds))
    except (config.ConfigError, pg.PgConfigError) as e:
        raise SystemExit(f"[admin] persisted config invalid: {e}")
    # Restore the generation stamped into the envelope so `/ready` stays green
    # across a `credproxy dev reload` (SIGHUP re-exec keeps the tmpfs). A file
    # written by an accepted push always carries `generation`; default 0 only
    # for a hand-crafted/legacy file (pre-release, no compat burden).
    generation = raw.get("generation", 0) if isinstance(raw, dict) else 0
    return AppState(creds=creds, pg_creds=pg_creds, generation=generation)


# ---- Middleware ----


@web.middleware
async def fetch_metadata_guard(request: web.Request, handler):
    """Reject cross-origin browser requests.

    Sec-Fetch-Site is a forbidden header name (browsers set it; JS
    cannot override). If present, require same-origin or none; if
    absent, the client isn't a browser -- allow.
    """
    sfs = request.headers.get("Sec-Fetch-Site")
    if sfs is not None and sfs not in ("same-origin", "none"):
        return web.json_response(
            {"error": "cross-origin requests forbidden"}, status=403
        )
    return await handler(request)


@web.middleware
async def no_store(request: web.Request, handler):
    resp = await handler(request)
    if isinstance(resp, web.StreamResponse):
        resp.headers["Cache-Control"] = "no-store"
    return resp


@web.middleware
async def access_log(request: web.Request, handler):
    log.emit("api", method=request.method, path=request.path)
    return await handler(request)


# ---- Admin handlers ----


def _auth_error(request: web.Request) -> web.Response | None:
    """Bearer-auth an /admin/* request. Returns an error Response to send, or
    None when the token is valid. The token is read from the bind mount per
    call, so host-side rotation works without a proxy restart."""
    header = request.headers.get("Authorization", "")
    scheme, _, presented = header.partition(" ")
    if scheme != "Bearer" or not presented:
        return web.json_response(
            {"error": "expected `Authorization: Bearer <token>`"}, status=401)
    try:
        token = TOKEN_PATH.read_text().strip()
    except OSError:
        return web.json_response({"error": "auth file unavailable"}, status=503)
    if not token or not hmac.compare_digest(presented, token):
        return web.json_response({"error": "invalid token"}, status=401)
    return None


async def admin_config(request: web.Request) -> web.Response:
    """POST /admin/config -- bearer-gated config push/reload."""
    state = request.app[STATE_KEY]

    # Authenticate before any body processing so unauthenticated probes can't
    # fingerprint config schema by reading 400 errors.
    err = _auth_error(request)
    if err is not None:
        return err

    try:
        body = await request.json()
    except json.JSONDecodeError:
        return web.json_response({"error": "invalid JSON body"}, status=400)

    try:
        generation = _accept_config(state, body)
    except (config.ConfigError, pg.PgConfigError) as e:
        return web.json_response({"error": str(e)}, status=400)
    log.emit("api", msg="config accepted", generation=generation)
    return web.json_response({"ok": True, "generation": generation})


def _accept_config(state: AppState, body: dict) -> int:
    """Validate `body` as a FULL config, swap it in under a freshly-bumped
    generation, persist the envelope, and return the new generation. Raises
    config.ConfigError / pg.PgConfigError on invalid config (the caller maps to
    400) WITHOUT touching state. Shared by the full push (`/admin/config`) and the
    surgical patch (`/admin/config/patch`), so both go through the exact same
    validate+swap path -- a patch is never a lighter-validated back door."""
    new_creds = config.load_resolved(body, source="POST /admin/config")
    new_pg = pg.load_pg(body, source="POST /admin/config",
                        reserved=pg.reserved_names(new_creds))

    # Carry the live runtime (re-seal) layer across the swap, so a routine
    # re-push (apply/start) doesn't drop an in-flight minted token's dynamic
    # placeholder. The static pushed layer is replaced; the runtime layer is
    # augmentable, not baked immutable at push time.
    new_creds.adopt_runtime(state.creds)

    # Bump the config generation on every accepted push (a validation failure
    # raises above without touching it). `/ready` gates on generation >= 1, so
    # this is the creds-ready signal that attached-workspace integrations poll.
    generation = state.generation + 1

    # The whole body (including an optional `fingerprint` the host sends to mark
    # this config version) is persisted to tmpfs, with `generation` folded into
    # the envelope so it survives a SIGHUP re-exec. `generation` is proxy-internal
    # bookkeeping the client never sends; we set it here so an incoming key can't
    # spoof it. load_resolved ignores keys other than `bindings`/`rules`.
    envelope = dict(body, generation=generation)
    _atomic_write(CONFIG_PATH, json.dumps(envelope).encode(), 0o400)
    # Swap both credential sets together (no await between, so an in-flight
    # request sees one consistent generation).
    state.creds = new_creds
    state.pg_creds = new_pg
    state.generation = generation
    return generation


async def admin_config_patch(request: web.Request) -> web.Response:
    """POST /admin/config/patch -- bearer-gated SURGICAL refresh of a subset of
    bindings by name.

    The workspace never sees this; the host CLI's `binding refresh` re-resolves
    only the named binding(s) and posts them here, so the proxy re-mints just
    those while every OTHER active binding's already-resolved secret (which the
    host does NOT cache) stays untouched. A full `/admin/config` re-push would
    re-invoke every active provider -- the pain this avoids when a short-lived
    token (gcloud ~1h) must be refreshed alongside a second costly binding.

    Body: `{"bindings": [<resolved wire binding>, ...], "fingerprint"?: <str>}`.
    Each entry is merged into the currently-held config BY NAME (it must already
    be present -- a patch refreshes a live binding, it does not create one), then
    the merged config goes through the SAME `_accept_config` validate+swap path as
    a full push (so a bad patch is rejected identically) and bumps the generation.
    Requires a config to already be loaded (409 otherwise -- push first)."""
    state = request.app[STATE_KEY]
    err = _auth_error(request)
    if err is not None:
        return err

    try:
        body = await request.json()
    except json.JSONDecodeError:
        return web.json_response({"error": "invalid JSON body"}, status=400)

    patch = body.get("bindings")
    if not isinstance(patch, list) or not patch:
        return web.json_response(
            {"error": "expected a non-empty `bindings` array to patch"}, status=400)

    if not CONFIG_PATH.exists():
        return web.json_response(
            {"error": "no config loaded; push a full config before patching"},
            status=409)
    try:
        current = json.loads(CONFIG_PATH.read_text())
    except (OSError, json.JSONDecodeError) as e:
        return web.json_response(
            {"error": f"held config unreadable: {e}"}, status=500)

    existing = current.get("bindings")
    existing = existing if isinstance(existing, list) else []
    index_by_name = {
        b.get("name"): i for i, b in enumerate(existing) if isinstance(b, dict)}
    merged = list(existing)
    patched: list[str] = []
    for entry in patch:
        if not isinstance(entry, dict):
            return web.json_response(
                {"error": "each patched binding must be an object"}, status=400)
        name = entry.get("name")
        if name not in index_by_name:
            return web.json_response(
                {"error": f"cannot patch binding '{name}': it is not in the loaded "
                          f"config (push or activate it first)"}, status=400)
        merged[index_by_name[name]] = entry
        patched.append(name)

    # Rebuild the full body with the merged bindings, carry the caller's new
    # fingerprint (metadata may be identical -> same fingerprint -> `enter` still
    # skips), and drop the old generation so `_accept_config` stamps a fresh one.
    new_body = dict(current)
    new_body["bindings"] = merged
    if "fingerprint" in body:
        new_body["fingerprint"] = body["fingerprint"]
    new_body.pop("generation", None)

    try:
        generation = _accept_config(state, new_body)
    except (config.ConfigError, pg.PgConfigError) as e:
        return web.json_response({"error": str(e)}, status=400)
    log.emit("api", msg="config patched", generation=generation, bindings=patched)
    return web.json_response(
        {"ok": True, "generation": generation, "patched": patched})


async def admin_config_get(request: web.Request) -> web.Response:
    """GET /admin/config -- bearer-gated. A SUPERSET response with two roles:

    1. `loaded` + `fingerprint` (read from the tmpfs config file) power the host's
       `enter` fast path -- it skips a redundant re-push when the proxy already
       holds the intended config's fingerprint. Config lives on tmpfs, so a
       restarted proxy reports `loaded: false` and the host re-pushes.
    2. `generation` + a SANITIZED `bindings`/`rules` projection report what the
       proxy is ACTUALLY running -- built from the LOADED config objects
       (`state.creds`/`.generation`), not a tmpfs re-read -- so `inspect`/`apply`/
       `doctor` can drift the resolved intent against reality (a proxy that lost
       its tmpfs on restart, or a stateless push from elsewhere).

    The projection is deliberately tighter than /setup -- NEVER a secret value,
    `params`, or a header/body value (see config.sanitized_live_config). Empty
    config (nothing loaded) returns generation 0 + empty lists, still 200."""
    state = request.app[STATE_KEY]
    err = _auth_error(request)
    if err is not None:
        return err
    loaded = False
    fingerprint = None
    if CONFIG_PATH.exists():
        try:
            fingerprint = json.loads(CONFIG_PATH.read_text()).get("fingerprint")
            loaded = True
        except (OSError, json.JSONDecodeError):
            loaded = False
    projection = config.sanitized_live_config(state.creds)
    return web.json_response({
        "loaded": loaded,
        "fingerprint": fingerprint,
        "generation": state.generation,
        "bindings": projection["bindings"],
        "rules": projection["rules"],
    })


async def admin_rule_test(request: web.Request) -> web.Response:
    """POST /admin/rule-test -- bearer-gated authoritative dry-run for the CLI's
    `rule test --live`. Body `{method, url}`. Runs the proxy's OWN rule matcher
    against the LOADED config and returns the ordered matches with exact per-script
    phase (from the compiled schemes) plus the intercept decision -- the ground
    truth the host-side matcher can only approximate. Read-only (no state change)."""
    from urllib.parse import urlsplit

    state = request.app[STATE_KEY]
    err = _auth_error(request)
    if err is not None:
        return err
    try:
        body = await request.json()
    except json.JSONDecodeError:
        return web.json_response({"error": "invalid JSON body"}, status=400)
    method, url = body.get("method"), body.get("url")
    if not isinstance(method, str) or not method or not isinstance(url, str) or not url:
        return web.json_response(
            {"error": "expected {method: str, url: str}"}, status=400)
    # Tolerate a bare host/path (no scheme) as well as a full URL.
    parts = urlsplit(url if "://" in url else "//" + url)
    host = (parts.hostname or "").lower()
    path = parts.path or "/"
    creds = state.creds
    return web.json_response({
        "method": method.upper(), "host": host, "path": path,
        "intercepted": creds.intercepts(host),
        "matches": creds.rule_set().dry_run(method, host, path),
    })


def _atomic_write(path: Path, data: bytes, mode: int) -> None:
    tmp = str(path) + ".tmp"
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "wb") as f:
        f.write(data)
    os.replace(tmp, path)


admin_routes = [
    web.post("/admin/config", admin_config),
    web.get("/admin/config", admin_config_get),
    web.post("/admin/config/patch", admin_config_patch),
    web.post("/admin/rule-test", admin_rule_test),
]
